### ISSUE TITLE
Error I don't know what is that

### ISSUE THREAD

**Issue by KikyoC** [PedroJM96/PixelLogin#4]
Hii,
I see this in my console. Can you help me ??

[20:14:35 ERROR]: Error occurred while enabling PixelLoginBukkit v2.1.2 (Is it up to date?)
com.pedrojm96.pixellogin.libs.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Packet for query is too large (5526600 > 1048576). You can change this value on the server by setting the max_allowed_packet' variable.

thank you very much and have a good day

**Comment by PedroJM96** [comment]
Change the database configuration to allow large packages.

**Comment by KikyoC** [comment]
Hi,
When I google this error, i need to set some values in files.

Is it possible to change that settings in phpmyadmin ?

**Comment by PedroJM96** [comment]
It is not possible, you can change this configuration through database commands.

SET GLOBAL max_allowed_packet=1073741824
