### ISSUE TITLE
Cannot connect to servers

### ISSUE THREAD

**Issue by LiWinDom** [PedroJM96/PixelLogin#6]
After installing the plugin on spigot and bungee nobody can join the server. Everybody have `Proxy lost connection to server` and `You have to join through the proxy` errors. In console plugin prints `Ocurrio un error al validar el token de LiWinDom en la base de datos`

- ip_forward is true,
- servers are on localhost
- database is also on localhost

Installed plugins:
- AntiAFKPlus
- Hibernate
- plasmovoice
- ProtocolLib
- TAB
- ViaVersion

**Comment by Avernys** [comment]
Make sure all the database are setuped correctly.

**Comment by Feraldragon** [comment]
update db

**Comment by PedroJM96** [comment]
You can show the error that you get in console.
